In [1]:
import pandas as pd
df = pd.read_excel('SerieA_2020-21.xlsx')

In [3]:
df.head()

,Stagione,Giornata,Team,Ruolo,Player,Voto1,FantaVoto1,Voto2,FantaVoto2,Voto3,FantaVoto3,Gf,Gv,Gs,Rp,Rs,Au,As
0,2020-21,1,ATALANTA,P,sportiello,6.5,5.5,6.5,5.5,6.5,5.5,-,-,1,-,-,-,-
1,2020-21,1,ATALANTA,D,romero,5.5,5.5,6.5,6.5,6.0,6,-,-,-,-,-,-,-
2,2020-21,1,ATALANTA,D,mojica,6.0,-,6.0,-,6.0,-,-,-,-,-,-,-,-
3,2020-21,1,ATALANTA,D,djimsiti,6.5,6,6.0,5.5,6.0,5.5,-,-,-,-,-,-,-
4,2020-21,1,ATALANTA,D,gosens,7.5,11.5,7.5,11.5,7.5,11.5,1,-,-,-,-,-,1

In [10]:
# raggruppa per squadra e media i voti
df.groupby('Team').mean()

            Giornata     Voto1     Voto2     Voto3
Team
ATALANTA    4.500000  6.066176  6.033088  6.062500
BOLOGNA     4.395349  5.922481  5.961240  5.965116
FIORENTINA  4.503817  5.870229  5.854962  5.854962
GENOA       4.500000  5.783088  5.816176  5.801471
INTER       4.511278  6.030075  6.052632  6.030075
JUVENTUS    4.738739  6.153153  6.157658  6.153153
LAZIO       4.500000  5.974265  5.937500  5.941176
MILAN       4.429688  6.253906  6.214844  6.277344
NAPOLI      4.626087  6.134783  6.121739  6.160870
ROMA        4.564516  6.241935  6.245968  6.266129
SAMPDORIA   4.430769  6.046154  5.976923  6.038462
SASSUOLO    4.481481  6.166667  6.151852  6.140741
TORINO      4.468750  5.855469  5.851562  5.871094
UDINESE     4.468254  5.892857  5.873016  5.880952
VERONA      4.503876  6.050388  6.050388  6.073643

In [12]:
# raggruppa per squadra e ruolo e media i voti
df.groupby(['Ruolo', 'Team']).mean()

                  Giornata     Voto1     Voto2     Voto3
Ruolo Team
A     ATALANTA    4.480000  6.100000  6.100000  6.080000
      BOLOGNA     4.162791  6.011628  6.023256  5.988372
      FIORENTINA  4.448276  5.793103  5.706897  5.724138
      GENOA       4.666667  5.925926  5.888889  5.888889
      INTER       4.434783  6.521739  6.500000  6.500000
...                    ...       ...       ...       ...
P     SAMPDORIA   4.500000  6.375000  6.312500  6.250000
      SASSUOLO    4.500000  6.312500  6.250000  6.312500
      TORINO      4.500000  5.812500  5.750000  5.812500
      UDINESE     4.500000  5.875000  5.875000  5.937500
      VERONA      4.500000  6.500000  6.375000  6.500000

[75 rows x 4 columns]

In [9]:
# raggruppa per squadra e ruolo e scegli il voto più alto
df.groupby(['Ruolo', 'Team']).max()

                 Stagione  Giornata      Player  Voto1 FantaVoto1  Voto2  \
Ruolo Team
A     ATALANTA    2020-21         8   zapata d.    7.5        9.5    7.5
      BOLOGNA     2020-21         8     vignato    8.0          9    8.0
      FIORENTINA  2020-21         8    vlahovic    7.5        9.5    7.5
      GENOA       2020-21         8  shomurodov    7.5        9.5    7.0
      INTER       2020-21         8     sanchez    8.0        9.5    7.5
...                   ...       ...         ...    ...        ...    ...
P     SAMPDORIA   2020-21         8      audero    7.0        6.5    6.5
      SASSUOLO    2020-21         8    consigli    7.0          7    6.5
      TORINO      2020-21         8      sirigu    7.0          6    7.0
      UDINESE     2020-21         8     nicolas    6.5          6    6.5
      VERONA      2020-21         8   silvestri    7.5          7    7.0

                 FantaVoto2  Voto3 FantaVoto3 Gf Gv Gs Rp Rs Au As
Ruolo Team
A     ATALANTA          9.5    7.5        9.5  2  1  -  -  -  -  1
      BOLOGNA           9.5    8.0          9  2  -  -  -  -  -  1
      FIORENTINA        9.5    7.5        9.5  1  -  -  -  -  -  2
      GENOA             9.5    7.0        9.5  1  -  -  -  -  -  1
      INTER             9.5    8.0        9.5  2  1  -  -  -  -  1
...                     ...    ...        ... .. .. .. .. .. .. ..
P     SAMPDORIA         6.5    6.5        6.5  -  -  3  -  -  -  1
      SASSUOLO          6.5    7.0          7  -  -  3  -  -  -  -
      TORINO              6    7.5        6.5  -  -  4  -  -  -  -
      UDINESE             6    6.5          6  -  -  3  -  -  -  -
      VERONA            6.5    7.5          7  -  -  2  -  -  -  -

[75 rows x 16 columns]